certificatesResolvers:
  cloudflare:
    acme:
      email: your_email
      storage: ./letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  file:
    filename: ./dynamic/dynamic.yaml
    watch: true

environment:
  - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}

# In your static configuration (traefik.yml or CLI args)
api:
  dashboard: true
  debug: true