http:
  routers:
    dashboard:
      rule: "Host(`domain`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      service: "api@internal"
      middlewares:
        - "dashboard-auth"
      tls:
        certResolver: "cloudflare"

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "hash"